### ISSUE TITLE
Instead of just the active or reserved GW IP Addresses we are also getting a list of subnets

### ISSUE THREAD

**Issue by ibenrodriguez** [PaloAltoNetworks/prisma-access-ip-api-client#2]
## Describe the bug

There is a defect in the python script API query so more information than what is desired is returned. Instead of just the active or reserved GW IP Addresses we are also getting a list of subnets.  

## Expected behavior

when using the switches --service-type gp_gateway --address-type active 

## Current behavior

Instead of just the active or reserved GW IP Addresses we are also getting a list of subnets.  

## Possible solution

need to fix the API or query such that only the selected results are returned.

## Steps to reproduce

This is the code being run. The results are wrong for both CSV and JSON output.

          python ./prisma-access-ip-api-client/run.py --service-type gp_gateway --address-type active --silent -k ${{secrets.panorama_api_key}} -f csv > ${{github.workspace}}/prisma-access-gw-ip.csv 
          python ./prisma-access-ip-api-client/run.py --service-type gp_gateway --address-type active --silent -k ${{secrets.panorama_api_key}} -f json > ${{github.workspace}}/prisma-access-gw-ip.json 
          python ./prisma-access-ip-api-client/run.py --service-type gp_gateway --address-type reserved --silent -k ${{secrets.panorama_api_key}} -f csv >> ${{github.workspace}}/prisma-access-gw-ip.csv 
          python ./prisma-access-ip-api-client/run.py --service-type gp_gateway --address-type reserved --silent -k ${{secrets.panorama_api_key}} -f json >> ${{github.workspace}}/prisma-access-gw-ip.json 

1.
2.
3.
4.

## Screenshots

Zone | service-type | entry-type | address | address-type | node_name | create_time | allow_listed
-- | -- | -- | -- | -- | -- | -- | --
  | Australia South | gp_gateway | address_detail | 66.159.210.124 | active |   | 1609804469 | False
  | Australia South | N/A | zone_subnet | 208.127.0.0/16 | N/A | N/A | N/A | N/A
  | Australia South | N/A | zone_subnet | 34.99.0.0/19 | N/A | N/A | N/A | N/A
  | Australia South | N/A | zone_subnet | 66.159.192.0/19 | N/A | N/A | N/A | N/A
  | Australia South | N/A | zone_subnet | 165.1.128.0/17 | N/A | N/A | N/A | N/A
  | Australia South | N/A | zone_subnet | 137.83.192.0/18 | N/A | N/A | N/A | N/A
  | Australia South | N/A | zone_subnet | 134.238.0.0/16 | N/A | N/A | N/A | N/A
  | Australia South | N/A | zone_subnet | 130.41.0.0/16 | N/A | N/A | N/A | N/A
  | South Korea | gp_gateway | address_detail | 52.79.180.130 | active |   | 1609802160 | False
  | South Korea | N/A | zone_subnet | 13.125.0.0/16 | N/A | N/A | N/A | N/A
  | South Korea | N/A | zone_subnet | 13.209.0.0/16 | N/A | N/A | N/A | N/A
  | South Korea | N/A | zone_subnet | 15.164.0.0/15 | N/A | N/A | N/A | N/A
  | South Korea | N/A | zone_subnet | 3.34.0.0/15 | N/A | N/A | N/A | N/A
  | South Korea | N/A | zone_subnet | 52.78.0.0/15 | N/A | N/A | N/A | N/A
  | South Korea | N/A | zone_subnet | 54.180.0.0/15 | N/A | N/A | N/A | N/A
  
  | Zone | service-type | entry-type | address | address-type | node_name | create_time | allow_listed
  | Australia Southeast | gp_gateway | address_detail | 66.159.209.13 | reserved |   | 1609804469 | False
  | Australia Southeast | N/A | zone_subnet | 208.127.0.0/16 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 34.99.0.0/19 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 66.159.192.0/19 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 165.1.128.0/17 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 137.83.192.0/18 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 134.238.0.0/16 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 130.41.0.0/16 | N/A | N/A | N/A | N/A
  | Australia Southeast | gp_gateway | address_detail | 66.159.209.129 | reserved |   | 1609801881 | False
  | Australia Southeast | N/A | zone_subnet | 208.127.0.0/16 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 34.99.0.0/19 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 66.159.192.0/19 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 165.1.128.0/17 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 137.83.192.0/18 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 134.238.0.0/16 | N/A | N/A | N/A | N/A
  | Australia Southeast | N/A | zone_subnet | 130.41.0.0/16 | N/A | N/A | N/A | N/A

## Context

We are running this manually and using ms excel to clean up data which is very time consuming and subject to human error. We need to be able to automate this and have it run accurately.  this report is used to monitor active gateways and control firewall access lists for our hundreds of users.

## Your Environment

running on github with github actions

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by bmigette** [comment]
https://github.com/PaloAltoNetworks/prisma-access-ip-api-client/commit/8a49d32f1ff0efc3f9b3c6a98674da9fca83904f (added a flag to print only subnets)
