### ISSUE TITLE
CSV output doesn´t include IPv6

### ISSUE THREAD

**Issue by ChristianDeckelmann** [PaloAltoNetworks/prisma-access-ip-api-client#3]
The CSV output doesn´t include IPv6 addresses.
The JSON output has them.

A very basic patch would be this:

--- a/prisma_access_ip_api_client/PrismaAccessIPApi.py
+++ b/prisma_access_ip_api_client/PrismaAccessIPApi.py
@@ -80,6 +80,19 @@ class PrismaAccessIPApiResult():
                         "N/A",
                         "N/A",
                     ])
+                )
+            for add_detail in result["address_details_v6"]:
+                r.append(
+                    ",".join([
+                        result["zone"],
+                        add_detail["serviceType"],
+                        "address_detail",
+                        add_detail["address"],
+                        add_detail["addressType"],
+                        " / ".join(add_detail['node_name']) if 'node_name' in add_detail else "",
+                        str(add_detail['create_time']) if 'create_time' in add_detail else "",
+                        str(add_detail['allow_listed']) if 'allow_listed' in add_detail else "",
+                    ])
                 )
         return "\n".join(r)

**Comment by bmigette** [comment]
Hello @ChristianDeckelmann, will look to add this, thanks for reporting this.

**Comment by bmigette** [comment]
Fixed in https://github.com/PaloAltoNetworks/prisma-access-ip-api-client/commit/8a49d32f1ff0efc3f9b3c6a98674da9fca83904f
